# Generated by Django 4.2.17 on 2025-01-13 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_session_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 0, 0)),
            preserve_default=False,
        ),
    ]
